# Encode user name and password like this:  
# echo -n "<USER>" | base64 
# echo -n "<PASSWORD>" | base64
---
apiVersion: v1
kind: Secret
metadata:
  name: cb-src-auth
type: Opaque
data:
  username: <BASE 64 ENCODED USER NAME>
  password: <BASE 64 ENCODED PASSWORD>

---
apiVersion: v1
kind: Secret
metadata:
  name: cb-tgt-auth
type: Opaque
data:
  username: <BASE 64 ENCODED USER NAME>
  password: <BASE 64 ENCODED PASSWORD>
