apiVersion: batch/v1
kind: Job
metadata:
  name: pillowfight
spec:
  template:
    metadata:
      name: pillowfight
    spec:
      containers:
      - name: pillowfight
        image: sequoiatools/pillowfight
        command: ["cbc-pillowfight",
                  "-U", "couchbase://cb-src-srv/cb-src?select_bucket=true",
                  "-I", "100000", "-B", "100", "-m", "100", "-M", "300", "-c", "-1", "-r", "100", "-t", "4", "-u", "Administrator", "-P", "<PASSWORD>"]
      restartPolicy: Never
