apiVersion: v1
kind: Secret
metadata:
  name: cb-tgt-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: <PASSWORD>
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-tgt
spec:
  networking:
    tls:
      rootCAs:
        - couchbase-server-ca
      secretSource:
        serverSecretName: couchbase-server-tls
        clientSecretName: couchbase-operator-tls
  image: couchbase/server:7.6.5
  #  autoscaleStabilizationPeriod: 60s
  antiAffinity: false
  autoResourceAllocation:
    cpuLimits: 2
    cpuRequests: 1
    enabled: true
    overheadPercent: 25
  security:
    adminSecret: cb-tgt-auth
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  platform: azure
  cluster:
    clusterName: HirschSource
    dataServiceMemoryQuota: 2Gi
    #indexServiceMemoryQuota: 256Mi
    #searchServiceMemoryQuota: 256Mi
    #eventingServiceMemoryQuota: 256Mi
    #analyticsServiceMemoryQuota: 1Gi
    autoFailoverTimeout: 120s
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120s
    autoFailoverServerGroup: false
    indexer:
      storageMode: plasma
  buckets:
    managed: true
  servers:
  - size: 3
    autoscaleEnabled: true
    name: data
    services:
    - data
    volumeMounts:
      default: couchbase
      data:  couchbase
  volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: "my-azure-disk-lazy-bound"
        resources:
          requests:
            storage: 100Gi
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: tgt
  labels:
    cluster: cb-tgt
spec:
  memoryQuota: 1024Mi
  storageBackend: magma
  evictionPolicy: fullEviction
